# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e57f651076deaf9a0464b4ab4e8bdea3"
name = "Deryan Variant Swatches"
application_url = "https://deryan-variant-swatches-staging.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://deryan-variant-swatches-staging.onrender.com/auth/callback",
  "https://deryan-variant-swatches-staging.onrender.com/auth/shopify/callback",
  "https://deryan-variant-swatches-staging.onrender.com/api/auth/callback"
]
